version: '3.8'

services:
  neo4j:
    image: neo4j:5
    container_name: neo4j-dev
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/pulkit123
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_plugins:/plugins

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant-dev
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_plugins:
  qdrant_storage:
